version: '3.7'

services:
  appnode:
    build: ./appnode
    # image: node:10.14.2
    ports: 
      - "8000:80"
    container_name: appnode
    tty: true
    environment: 
      - PORT=80
    volumes:
      - ../schedule-arranger:/src
    working_dir: "/src"

  postgres:
    build: ./postgres
    # image: postgres:10.16
    ports: 
      - "33060:3306"
    container_name: postgres
    tty: true
    working_dir: "/"